### ISSUE TITLE
Test is not very robust

### ISSUE THREAD

**Issue by sammarcus** [learn-co-curriculum/guessing-cli#2]
Solution only checks 2 numbers. It does not check against common scenarios such as a wrong range (not allowing `rand` up to `6`), or even if the student has permitted `rand` to return `0`, either.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by maxwellbenton** [comment]
Hi @sammarcus,

Thank you for opening this issue and providing this feedback. This lab has been updated and is currently being used in our prework content. Because it is early in the course, we've actually simplified this lab's tests and repurposed it mainly as practice for basic application creation, user input, and conditional flow. We will not be able to incorporate the changes you suggest, but appreciate your feedback.

Hope all is well!
